services:
  artem-fitisov-web-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artem-fitisov-web-backend
    working_dir: /app/backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    env_file:
      - ./backend/.env
    environment:
      PUBLIC_BACKEND_URL: https://obzvonai.ru
    volumes:
      - ./backend:/app/backend
    ports:
      - "8002:8000"
    restart: unless-stopped

  artem-fitisov-web-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: artem-fitisov-web-frontend
    ports:
      - "3002:80"
    depends_on:
      - artem-fitisov-web-backend
    restart: unless-stopped
